steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/GoogleCloudPlatform/cloud-builders']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'docker'
  args:
  - 'version'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'docker'
  args:
  - 'info'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'docker'
  args:
  - 'images'

- name: 'debian:jessie'
  args:
  - 'pwd && ls'