steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'docker'
  args:
  - 'version'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'env'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'docker'
  args:
  - 'info'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'docker'
  args:
  - 'images'

- name: 'debian:jessie'
  args: ['bash', '-c', 'ls']